### ISSUE TITLE
Every signature should have a description what the procedure/syntax does

### ISSUE THREAD

**Issue by wasamasa** [schemeorg-community/index.scheme.org#31]
This seems like a very obvious omission and would greatly increase the utility of the project. Given that it's using solr, this should be mostly about data entry. Once all signatures are documented, additional features such as search by description can be added.

**Comment by arvyy** [comment]
Absolutely true. I decided to prioritize getting broad but shallow completion first, instead of trying to do it all in-depth from the get go but burnout midway through. As an intermediate solution I've planned to include an easy way to navigate to upstream documentation that contains description #27

**Comment by APIPLM** [comment]
Yes. As we are talking about the `docstring `  of the procedure in scheme, sound like more than what we saw in Java like the description of the function (input description and output description), but also kind of have the usage of the procedure  the explanation of the procedure  and so on. Then rather than go to the linker of the documentation of the procedure to have a look at.
